PR for test  Review code Procces (self review)
ivanmvh/microverse-ivan-inaki-main-2 pull request #1
Opened 2022-09-26 16:37 UTC by ivanmvh

2022-09-26 17:27 UTC, ivanmvh commented
Please do you have linters errors. Remember that a norm is that you cant ask for a review if you have linters errors. 🙏 
![image](https://user-images.githubusercontent.com/817718/192341741-fde0143f-33fc-4da9-88d1-723d743f374d.png)

2022-09-26 17:58 UTC, ivanmvh reviewed
Please your code have linters errors. Remember you can't ask for a review if you had linters errors.
![image](https://user-images.githubusercontent.com/817718/192347247-c7f98b57-37cf-46a9-919b-97a90ac30dae.png).

2022-09-26 18:05 UTC, ivanmvh reviewed
Please do the changues required.

2022-09-26 18:05 UTC, ivanmvh commented on index.html
> +    We are a Microverse programer - Thechnical Documentation Page (Project)
A text must be enclosed between tags. For example <h1></h1> or h2, h3 o p.

2022-09-26 18:18 UTC, frank1738 requested changes
Hi @ivanmvh , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![YesYouAreGIF (2)](https://user-images.githubusercontent.com/50941074/172881298-64e98170-87c5-4075-8a77-71d65d991f55.gif)


## Highlights

✅ Correct use of Github inline comments


## Required Changes ♻️
- [ REQUIRED] Kindly provide a description to your Pull Request Describing what you did. This is important for documentation purposes
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-26 18:18 UTC, frank1738 commented on index.html
> +    We are a Microverse programer - Thechnical Documentation Page (Project)
> A text must be enclosed between tags. For example
> 
> or h2, h3 o p.

- [ ] Good work using inline comments 👍 . However, Kindly try to explain the reason as to `why?` you are requesting this change. The would enable the other person understand you clearly
- [ ] Kindly provide at least two reviews.

2022-09-26 23:30 UTC, ivanmvh commented
STATUS: REQUIRED CHANGES ♻️
Hi @ivanmvh 👋

Your project page is looking fantastic so far 🤩 !

However, there is still some room for improvement, that can help you have better code and make your project professional 😎

2022-09-26 23:32 UTC, ivanmvh commented
Highlights ✨
Great work using the right GitHub Flow 💯

Commits are descriptive and meaningful 👍
Project Documentation (PR, README) is professional 👔
Congrats on your work so far! 👏

Required Changes ♻️
There are some issues that you still need to work on to go to the next project, but you are almost there!
For more information, check the comments under the review ⬇️

Optional suggestions ☑️
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can improve the quality of your code 💯

Happy coding and keep it up! 🙌

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Nyame-Wolf in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

2022-09-27 00:01 UTC, ivanmvh reviewed
STATUS: REQUIRED CHANGES ♻️
Hi @ivanmvh 👋

Your project page is looking fantastic so far 🤩 !

However, there is still some room for improvement, that can help you have better code and make your project professional 😎

Highlights ✨
Great work using the right GitHub Flow 💯
Great work using the same font as Figma design ☑️
Commits are descriptive and meaningful 👍
Project Documentation (PR, README) is professional 👔
Congrats on your work so far! 👏

Required Changes ♻️
There are some issues that you still need to work on to go to the next project, but you are almost there!
For more information, check the comments under the review ⬇️

Optional suggestions ☑️
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can improve the quality of your code 💯

Happy coding and keep it up! 🙌

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @ivanmvh  in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

2022-09-27 00:01 UTC, ivanmvh commented on index.html
>      <main id="main-doc">Hello
I suggest you fix the margins of the main section. Currently your content seems squeezed yet you have a lot of empty space left.

2022-09-27 00:01 UTC, ivanmvh commented on index.html
>          <header>topic1 </header>
Kindly note that it is a requirement that you match the design as much as you can. Currently the cards in this section have too much margins. Please fix this:
![image](https://user-images.githubusercontent.com/817718/192401246-986964af-84c6-4a51-87f0-f0bbd8b0968e.png)

2022-09-27 00:09 UTC, mgmediaweb requested changes
Hi @ivanmvh , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that Linters not passed

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-09-28 16:30 UTC, ivanmvh commented
STATUS: REQUIRED CHANGES ♻️
Hi @ivanmvh 👋

Your project page is looking fantastic so far 🤩 !

However, there is still some room for improvement, that can help you have better code and make your project professional 😎

Highlights ✨
Great work using the right GitHub Flow 💯
Great work using the same font as Figma design ☑️
Commits are descriptive and meaningful 👍
Project Documentation (PR, README) is professional 👔
Congrats on your work so far! 👏

Required Changes ♻️
There are some issues that you still need to work on to go to the next project, but you are almost there!
For more information, check the comments under the review ⬇️

Optional suggestions ☑️
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can improve the quality of your code 💯

Happy coding and keep it up! 🙌

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @ivanmvh in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

2022-09-28 18:18 UTC, ivanmvh commented on css/styles.css
> +  /* position: absolute */
You should not leave unused lines of code as comments unless there is a reason why that commented code is there. If there is no valid reason delete those comments that make your code not clean. 🧹

2022-09-28 18:18 UTC, ivanmvh commented on index.html
> +    We are a Microverse programer - Thechnical Documentation Page (Project) -ivmvh
This text must be enclosed in some class of tag depending of his semantic meaning.  If is a Title could be <p> y is a title use h1,h2 or h3.
https://www.w3schools.com/html/html5_semantic_elements.asp

2022-09-28 18:25 UTC, Abenezer-Tilahun approved these changes
Hi @ivanmvh     ,

### Status: Approved ✔️ ✔️ ✔️

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

Cheers and Happy coding!👏👏👏
## Optional Suggestion

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-09-29 05:17 UTC, merged